### ISSUE TITLE
Magisk log: "e 432:569 sendfile failed with 2: No such file or directory"

### ISSUE THREAD

**Issue by iqubik** [Magisk-Modules-Repo/Magisk-Manager-for-Recovery-Mode#1]
Magisk log: "e 432:569 sendfile failed with 2: No such file or directory"

Any Modules can not find after install this
New modules installs but not works and not shows on list of android magisk manager.

Very Poor soft! Need to repair system after that!
Unistall_magisk.zip not repair this error!
I lost my system???

Android AOSP (Aex) latest 7.1.2
Xiaomi redmi 4x

**Comment by iqubik** [comment]
Please Do correct unistaller

**Comment by VR-25** [comment]
You should't attempt to install it from Magisk Manager. When I released this tool, I explicitly stated that this is not meant to be installed/used in boot mode -- only in recovery mode. Why would you consider the opposite? Besides, the name "Magisk Manager for Recovery Mode" should've told you all.

Anyway, hopefully you got your issues fixed. The latest version won't allow you to make such a mistake again. Enjoy using the tool as much as I enjoyed writing it. Any other issues, please, report, report, report -- I'm always willing to solve that kind of puzzle.

P.S., please, re-read the README before installing updates, as there might be new things you'e not aware of.

**Comment by iqubik** [comment]
I find bad module - youtube magisk module. When i install MMR also i
install youtube hack and magisk youtube have very large name of file and
broke all.
I recover my system but have a little scare to install another modules.
Thank you to you reply. And thank for a work with this pussles :)

23 нояб. 2017 г. 22:10 пользователь "VR-25" <notifications@github.com>
написал:
